import { createHash } from 'node:crypto';
import type { ExportResult, ProfessionalReport, ReportFormat } from '../types.js';

function exportSized(
  format: ReportFormat,
  contentType: string,
  filename: string,
  body: string,
): ExportResult {
  return {
    format,
    contentType,
    filename,
    body,
    byteSize: Buffer.byteLength(body, 'utf8'),
  };
}

export function exportJson(report: ProfessionalReport): ExportResult {
  return exportSized(
    'json',
    'application/json; charset=utf-8',
    slug(report, 'json'),
    JSON.stringify(report, null, 2),
  );
}

export function exportCsv(report: ProfessionalReport): ExportResult {
  const rows = [
    ['section', 'priority', 'title', 'summary', 'effort', 'business', 'technical'],
    ...report.recommendations.map((r) => [
      'recommendation',
      r.priority,
      csv(r.title),
      csv(r.summary),
      String(r.effortEstimate),
      csv(r.businessImpact?.explanation ?? ''),
      csv(r.technicalImpact?.explanation ?? ''),
    ]),
    ...report.findingsSummary.top.map((f) => [
      'finding',
      f.severity,
      csv(f.title),
      csv(f.description ?? ''),
      '',
      csv(f.category),
      csv(f.location ?? ''),
    ]),
  ];
  const body = rows.map((r) => r.join(',')).join('\n');
  return exportSized('csv', 'text/csv; charset=utf-8', slug(report, 'csv'), body);
}

export function exportHtml(report: ProfessionalReport, asPdf = false): ExportResult {
  const cats = report.categoryScores
    .map(
      (c) =>
        `<tr><td>${esc(c.label)}</td><td>${c.score}</td><td>${c.weight}</td></tr>`,
    )
    .join('');
  const recs = report.recommendations
    .map(
      (r) => `<article class="rec">
  <h3><span class="pill">${esc(r.priority)}</span> ${esc(r.title)}</h3>
  <p>${esc(r.summary)}</p>
  <div class="grid">
    <div><strong>Business</strong><p>${esc(r.businessImpact?.explanation ?? '—')}</p>
      <p class="muted">${esc(r.businessImpact?.estimatedBenefit ?? '')}</p></div>
    <div><strong>Technical</strong><p>${esc(r.technicalImpact?.explanation ?? '—')}</p>
      <p class="muted">Effort: ${esc(String(r.effortEstimate))} · ${esc(r.effortHoursHint)}</p></div>
  </div>
  ${r.actions?.length ? `<ul>${r.actions.map((a) => `<li>${esc(a)}</li>`).join('')}</ul>` : ''}
</article>`,
    )
    .join('\n');

  const body = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(report.title)}</title>
<style>
  body{font-family:Georgia,serif;max-width:880px;margin:40px auto;padding:0 24px;color:#0f172a;line-height:1.5}
  h1{font-size:1.8rem;margin-bottom:.25rem} .muted{color:#64748b}
  .score{font-size:2.4rem;font-weight:700} table{width:100%;border-collapse:collapse;margin:1rem 0}
  th,td{border-bottom:1px solid #e2e8f0;padding:.5rem;text-align:left}
  .pill{display:inline-block;background:#e2e8f0;border-radius:999px;padding:.1rem .55rem;font-size:.75rem;text-transform:capitalize}
  .rec{border:1px solid #e2e8f0;border-radius:8px;padding:1rem;margin:1rem 0}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}
  @media print{body{margin:0} .rec{break-inside:avoid}}
</style>
</head>
<body>
  <header>
    <p class="muted">${esc(report.organizationName ?? 'Inspectra')} · ${esc(report.generatedAt)}</p>
    <h1>${esc(report.title)}</h1>
    <p class="muted">${esc(report.target.label)}${report.target.type ? ` · ${esc(report.target.type)}` : ''}</p>
    <p class="score">${report.overallScore}<span class="muted" style="font-size:1rem"> / 100</span></p>
  </header>
  <section>
    <h2>Executive summary</h2>
    <p>${esc(report.executiveSummary)}</p>
  </section>
  <section>
    <h2>Category scores</h2>
    <table><thead><tr><th>Category</th><th>Score</th><th>Weight</th></tr></thead><tbody>${cats}</tbody></table>
    ${report.formula ? `<p class="muted">${esc(report.formula)}</p>` : ''}
  </section>
  <section>
    <h2>Recommendations & effort</h2>
    <p class="muted">Rollup: ${esc(report.effortSummary.estimatedHoursRange)} across ${report.effortSummary.totalItems} item(s).</p>
    ${recs || '<p class="muted">No recommendations.</p>'}
  </section>
  <section>
    <h2>Findings summary</h2>
    <p>${report.findingsSummary.total} finding(s) —
      ${Object.entries(report.findingsSummary.bySeverity)
        .map(([k, v]) => `${esc(k)}: ${v}`)
        .join(' · ') || 'none'}
    </p>
  </section>
  <footer class="muted"><p>Generated by ${esc(report.generatedBy)} · schema ${report.schemaVersion}${asPdf ? ' · print to PDF' : ''}</p></footer>
</body>
</html>`;

  if (asPdf) {
    return exportSized('pdf', 'text/html; charset=utf-8', slug(report, 'pdf.html'), body);
  }
  return exportSized('html', 'text/html; charset=utf-8', slug(report, 'html'), body);
}

export function exportSarif(report: ProfessionalReport): ExportResult {
  const results = report.findingsSummary.top.map((f) => ({
    ruleId: f.fingerprint.slice(0, 64) || f.category,
    level: severityToSarif(f.severity),
    message: { text: f.title },
    locations: f.location
      ? [{ physicalLocation: { artifactLocation: { uri: f.location } } }]
      : undefined,
    properties: {
      category: f.category,
      description: f.description,
      remediation: f.remediation,
    },
  }));

  const doc = {
    $schema: 'https://json.schemastore.org/sarif-2.1.0.json',
    version: '2.1.0',
    runs: [
      {
        tool: {
          driver: {
            name: 'Inspectra AI',
            informationUri: 'https://inspectra.ai',
            version: '0.1.0',
            rules: report.findingsSummary.top.map((f) => ({
              id: f.fingerprint.slice(0, 64) || f.category,
              name: f.title,
              shortDescription: { text: f.title },
              fullDescription: { text: f.description || f.title },
              properties: { severity: f.severity, category: f.category },
            })),
          },
        },
        results,
        properties: {
          overallScore: report.overallScore,
          auditId: report.auditId,
          effortSummary: report.effortSummary,
        },
      },
    ],
  };

  return exportSized(
    'sarif',
    'application/sarif+json; charset=utf-8',
    slug(report, 'sarif.json'),
    JSON.stringify(doc, null, 2),
  );
}

export function exportReport(
  report: ProfessionalReport,
  format: ReportFormat,
): ExportResult {
  switch (format) {
    case 'csv':
      return exportCsv(report);
    case 'html':
      return exportHtml(report, false);
    case 'pdf':
      return exportHtml(report, true);
    case 'sarif':
      return exportSarif(report);
    case 'json':
    default:
      return exportJson(report);
  }
}

export function checksumSha256(body: string | Buffer): string {
  return createHash('sha256').update(body).digest('hex');
}

function slug(report: ProfessionalReport, ext: string): string {
  const base = report.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48);
  return `${base || 'inspectra-report'}.${ext}`;
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function csv(s: string): string {
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function severityToSarif(severity: string): 'error' | 'warning' | 'note' {
  if (severity === 'critical' || severity === 'high') return 'error';
  if (severity === 'medium') return 'warning';
  return 'note';
}
